### ISSUE TITLE
Step 6: 📝 Create a Low-fidelity wireframe

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v44-tier3-team-29#11]
**Objective**

Establish a common understanding across the team of what information is in each screen and the actions that may be invoked from each screen.

**How**

- [x]  Using the features you added to the the Feature Planning template in step 4 identify the screens you’ll need and the information on each one.
- [x]  Map the actions users will be able to perform from each screen and the navigation from screen-to-screen
- [x]  Create a low-fidelity wireframe using a tool like [[Figma](https://www.figma.com/)](https://www.figma.com/) or even pencil and paper.

**Resources**

[How To Wireframe A Website in 3 Easy Steps](https://elementor.com/blog/wireframe-website/)
[Create a low fidelity wireframe (Chingu Handbook)](https://www.notion.so/chingucohorts/Voyages-1e528dcbf1d241c9a93b4627f6f1c809#0aa05f393d1f48059ee9ff7fdfef4e78)

**Member of Epic:** #16

**Comment by ha-anna** [comment]
I have created a low-fidelity wireframe using Freeform (web only for now) as well as our project's brand identity.
- [Brand Identity](https://www.figma.com/file/gIMuiPKE8ANS6M1UsCSnTc/%5BARTEMIS%5D-Brand-identity?type=design&node-id=0%3A1&t=IXoNXLWxheFcm3aE-1)


![Artemis_lf_wireframes](https://user-images.githubusercontent.com/83631167/236633367-0acb5bfe-7966-4a90-8cd3-df0fa39dc03d.png)

**Comment by ha-anna** [comment]
Working on [high-fidelity wireframes](https://www.figma.com/file/ZYLqiaISIJpINTZkqLgGhV/%5BARTEMIS%5D-Wireframes?type=design&node-id=0%3A1&t=jFiINqF70XmHzOau-1) now.
![Screen Shot 2023-05-09 at 11 36 26 PM](https://github.com/chingu-voyages/v44-tier3-team-29/assets/83631167/e469bc46-4d3f-4b73-98d1-48b483d87aff)
