### ISSUE TITLE
Create Sign In and Sign Up pages

### ISSUE THREAD

**Issue by ha-anna** [chingu-voyages/v44-tier3-team-29#22]
**__Task Description__**
Create Sign In and Sign Up pages based on [the wireframes](https://www.figma.com/file/ZYLqiaISIJpINTZkqLgGhV/%5BARTEMIS%5D-Wireframes?type=design&t=LSKkxDgTGCGkFGj9-1)

**__Technical Considerations__**
Use TailwindCSS and follow accessibility rules, semantic HTML, and make it responsive.

**__Additional Considerations__**
![Screen Shot 2023-05-18 at 10 50 40 PM](https://github.com/chingu-voyages/v44-tier3-team-29be/assets/83631167/5f617876-d0c5-46b9-8f98-43a8b4a82de7)

![Screen Shot 2023-05-18 at 10 50 53 PM](https://github.com/chingu-voyages/v44-tier3-team-29be/assets/83631167/64523bf0-a902-493b-952b-c5071d790bb6)

**Comment by leixdd** [comment]
I have created a PR for this task. #32

Thank you very much.

**Comment by ha-anna** [comment]
Completed!
